image: docker:latest
services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo $IMAGE_TAG
    - docker build -t $IMAGE_TAG ./src/
    - docker push $IMAGE_TAG