
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AMP COMMA DUR END INT LBRACKET LPAREN NEWLINE PLAY RBRACKET RPAREN START TWOPOINTSp_play : PLAY TWOPOINTS LBRACKET seqacc RBRACKETseqacc : accseqacc : acc COMMA seqaccacc : LPAREN seqnotas RPARENacc : notaseqnotas : notaseqnotas : nota COMMA seqnotasnota : INT'
    
_lr_action_items = {'PLAY':([0,],[2,]),'$end':([1,10,],[0,-1,]),'TWOPOINTS':([2,],[3,]),'LBRACKET':([3,],[4,]),'LPAREN':([4,11,],[7,7,]),'INT':([4,7,11,16,],[9,9,9,9,]),'RBRACKET':([5,6,8,9,14,15,],[10,-2,-5,-8,-3,-4,]),'COMMA':([6,8,9,13,15,],[11,-5,-8,16,-4,]),'RPAREN':([9,12,13,17,],[-8,15,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'p_play':([0,],[1,]),'seqacc':([4,11,],[5,14,]),'acc':([4,11,],[6,6,]),'nota':([4,7,11,16,],[8,13,8,13,]),'seqnotas':([7,16,],[12,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> p_play","S'",1,None,None,None),
  ('p_play -> PLAY TWOPOINTS LBRACKET seqacc RBRACKET','p_play',5,'p_play_seq','calcyacc.py',14),
  ('seqacc -> acc','seqacc',1,'p_seqacc_acc','calcyacc.py',18),
  ('seqacc -> acc COMMA seqacc','seqacc',3,'p_seqacc_accseqacc','calcyacc.py',22),
  ('acc -> LPAREN seqnotas RPAREN','acc',3,'p_acc_seqnotas','calcyacc.py',26),
  ('acc -> nota','acc',1,'p_acc_nota','calcyacc.py',30),
  ('seqnotas -> nota','seqnotas',1,'p_seqnotas_nota','calcyacc.py',34),
  ('seqnotas -> nota COMMA seqnotas','seqnotas',3,'p_seqnotas_notaseqnotas','calcyacc.py',38),
  ('nota -> INT','nota',1,'p_nota_int','calcyacc.py',42),
]
