
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A428AE36340B657044123473A754ADE8'
    
_lr_action_items = {'PLAY':([3,12,],[4,4,]),'END':([6,12,17,],[11,-2,-3,]),'LPAREN':([15,25,],[21,21,]),'INT':([13,14,15,21,25,31,],[18,19,22,22,22,22,]),'RPAREN':([22,26,27,32,],[-14,30,-12,-13,]),'NEWLINE':([1,5,7,11,18,19,28,],[3,-4,12,16,-5,-6,-7,]),'LBRACKET':([10,],[15,]),'START':([0,],[1,]),'COMMA':([20,22,23,27,30,],[25,-14,-11,31,-10,]),'TWOPOINTS':([4,8,9,],[10,13,14,]),'AMP':([3,12,],[8,8,]),'DUR':([3,12,],[9,9,]),'RBRACKET':([20,22,23,24,29,30,],[-8,-14,-11,28,-9,-10,]),'$end':([2,16,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'acc':([15,25,],[20,20,]),'assignation':([3,12,],[5,5,]),'program2':([0,],[2,]),'seqnotas':([21,31,],[26,32,]),'program':([3,12,],[6,17,]),'nota':([15,21,25,31,],[23,27,23,27,]),'statement':([3,12,],[7,7,]),'expression':([15,25,],[24,29,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program2","S'",1,None,None,None),
  ('program2 -> START NEWLINE program END NEWLINE','program2',5,'p_program2','apollo_yacc.py',14),
  ('program -> statement NEWLINE','program',2,'p_program_statement_newline','apollo_yacc.py',18),
  ('program -> statement NEWLINE program','program',3,'p_program_statement_program','apollo_yacc.py',22),
  ('statement -> assignation','statement',1,'p_statement_assignation','apollo_yacc.py',26),
  ('assignation -> AMP TWOPOINTS INT','assignation',3,'p_assignation_AMP','apollo_yacc.py',30),
  ('assignation -> DUR TWOPOINTS INT','assignation',3,'p_assignation_DUR','apollo_yacc.py',34),
  ('assignation -> PLAY TWOPOINTS LBRACKET expression RBRACKET','assignation',5,'p_assignation_PLAY','apollo_yacc.py',38),
  ('expression -> acc','expression',1,'p_seqacc_acc','apollo_yacc.py',42),
  ('expression -> acc COMMA expression','expression',3,'p_seqacc_accseqacc','apollo_yacc.py',46),
  ('acc -> LPAREN seqnotas RPAREN','acc',3,'p_acc_seqnotas','apollo_yacc.py',50),
  ('acc -> nota','acc',1,'p_acc_nota','apollo_yacc.py',54),
  ('seqnotas -> nota','seqnotas',1,'p_seqnotas_nota','apollo_yacc.py',58),
  ('seqnotas -> nota COMMA seqnotas','seqnotas',3,'p_seqnotas_notaseqnotas','apollo_yacc.py',62),
  ('nota -> INT','nota',1,'p_nota_int','apollo_yacc.py',66),
]
